// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3X8mNpAGqEhmhuUiypUj1P-MQshG2ycs',
    appId: '1:737154946294:web:b816cfcb25789743a748d7',
    messagingSenderId: '737154946294',
    projectId: 'chatapp-4e347',
    authDomain: 'chatapp-4e347.firebaseapp.com',
    databaseURL: 'https://chatapp-4e347-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-4e347.appspot.com',
    measurementId: 'G-7JDWN204JK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVG-a9l-f9OnxdgEgxsh6AE30IY3zO9dg',
    appId: '1:737154946294:android:b7722e7574c2184da748d7',
    messagingSenderId: '737154946294',
    projectId: 'chatapp-4e347',
    databaseURL: 'https://chatapp-4e347-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-4e347.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm0Qm2EH-wXvtqsxN_734TYRDzovZGPkk',
    appId: '1:737154946294:ios:05f59d87072b6cfea748d7',
    messagingSenderId: '737154946294',
    projectId: 'chatapp-4e347',
    databaseURL: 'https://chatapp-4e347-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-4e347.appspot.com',
    androidClientId: '737154946294-530tiijgnp59nh2eo4f0jvbkgiq7720v.apps.googleusercontent.com',
    iosBundleId: 'com.example.wbrs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCm0Qm2EH-wXvtqsxN_734TYRDzovZGPkk',
    appId: '1:737154946294:ios:05f59d87072b6cfea748d7',
    messagingSenderId: '737154946294',
    projectId: 'chatapp-4e347',
    databaseURL: 'https://chatapp-4e347-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-4e347.appspot.com',
    androidClientId: '737154946294-530tiijgnp59nh2eo4f0jvbkgiq7720v.apps.googleusercontent.com',
    iosBundleId: 'com.example.wbrs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3X8mNpAGqEhmhuUiypUj1P-MQshG2ycs',
    appId: '1:737154946294:web:319614022b50c8afa748d7',
    messagingSenderId: '737154946294',
    projectId: 'chatapp-4e347',
    authDomain: 'chatapp-4e347.firebaseapp.com',
    databaseURL: 'https://chatapp-4e347-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-4e347.appspot.com',
    measurementId: 'G-4N2B6EDD4B',
  );

}